
CREATE DATABASE "php_todo";

CREATE TABLE "items" (
    "id" SERIAL PRIMARY KEY,
    "name" varchar(255) NOT NULL,
	"done" BOOLEAN NOT NULL DEFAULT FALSE,
	"created" DATE NOT NULL DEFAULT CURRENT_DATE
);